name: worklogs_jira
description: This is a small project in Flutter about work logs in Jira.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  http: ^1.1.0
  intl: any
  msix: ^3.16.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf

  assets:
    - assets/.env.development
    - assets/.env.production
    - assets/images/
